name: deploy-to-server

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy-to-server:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_DATAFRAMETRAINER_KEY }}
        known_hosts: 'just-a-placeholder-to-not-get-errors'
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.DATAFRAMETRAINER_SERVER_IP }} >> ~/.ssh/known_hosts
      working-directory: ./
    - name: Rsync to server
      run: rsync -avz . dataframetrainer@${{ secrets.DATAFRAMETRAINER_SERVER_IP}}:/home/dataframetrainer/prod/
    # - name: Run docker compose
    #   run: |
    #     ssh dataframetrainer@${{ secrets.DATAFRAMETRAINER_SERVER_IP}} "cd /home/dataframetrainer/prod && make down && make cleanup_prod && make prod_detached"